name: naishma application

on: push

jobs:
  job-one:
    runs-on: ubuntu-latest

    steps:
      - name: checkout to scm
        uses: actions/checkout@v3

      - name: install dependencies
        run: npm install

      - name: build the application
        run: npm run build

      - name: test the application
        run: npm test


   

        